// Generated by go run gen.go
// Do not edit.
// This file must be included in .gitignore.

package version

const (
	// Major version when you make incompatible API changes.
	Major = 0

	// Minor version when you add functionality in a backwards-compatible manner.
	Minor = 2

	// Patch version when you make backwards-compatible bug fixes.
	Patch = 0

	// PreRelease version may be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.
	PreRelease = ""

	// BuildTime is build metadata and it may be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version.
	BuildTime = "20170210194126"

	// GitCommit is build metadata and it may be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version.
	GitCommit = "8bc4b6f3"
)
